# Site settings
title: Abelx's Blog
name: Abelx's Blog # your name
email: theabelx@163.com # your email address
description: >
    New blog, just to record. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abelx.github.io"  #the base hostname & protocol for your site
twitter_username: itisbenjamin1 # your Twitter username
github_username: abelx # your Github username
disqus_username: itisbenjamin # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
